fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type:     annotation
